# Menus
menu:
  Home:
    link: .
    link_icon: fa-home
  Archives:
    link: archives
    link_icon: fa-folder
  Categories:
    link: categories
    link_icon: fa-copy
  Tags:
    link: tags
    link_icon: fa-tags
  About:
    link: about
    link_icon: fa-info-circle

# Customize
customize:
    logo:
        mini: xhl
        lg: 夏红林
    profile:
        enabled: true # Whether to show profile bar
        user_image: /img/xiahl.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        user_name: Xiahl
        user_title: Web Developer & Designer
        user_location: Shenzhen, China
        follow: https://github.com/Xiahl1990
    highlight: monokai
    layout:
        skin: skin-blue
    sidebar: right # sidebar position, options: left, right
    control_sidebar:
        bg_color: control-sidebar-dark
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: favicon.ico # path to favicon
    social_links:
      Email:
        link: "mailto:xiahl1990@gmail.com"
        link_icon: fa-email
        bg_color: "#90C9E2"
      GitHub:
        link: "https://github.com/Xiahl1990"
        link_icon: fa-github
        bg_color: "#F5F5F5"
      RSS:
        link: "/atom.xml"
        link_icon: fa-rss
        bg_color: "#EB965D"
      WeiBo:
        link: ""
        link_icon: fa-weibo
        bg_color: "#E8CA86"
      WeiXin:
        link: ""
        link_icon: fa-weixin
        bg_color: "#27AE60"
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Fancybox thumb
fancybox_thumb:
        FFzTVldq:
        FFzWjuxY:
        FFzTXdbO:
        FFzU4h8I:
        FFzU8XM8:
        FFzUaXCt:
        FFzUi3nZ:
        FFzUi8gf:
        FFzUlgux:
        FFzUpGUm:
        FFzUr0NG:
        FFzUs57o:
        FFzUKwpK:
        FFzVl5d0:
        FFzVAiM8:
        FFzW1a8u:
        FFzW8DZ9:
        FFzWfBUl:


# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: #eNk1MFFt1dSM2c_F8Mv7 # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Conments
preload_comment: true
disqus:
  on: true
  shortname: xiahl
duoshuo:
  #on: true
  domain:
youyan:
  #on: true
  id:

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io

# CDN
bootcdn:
    bootstrap_css: //cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.css
    bootstrap_min_css: //cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css
    bootstrap_js: //cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.js
    bootstrap_min_js: //cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js

    bootstrap_datepicker3_css: //cdn.bootcss.com/bootstrap-datepicker/1.6.1/css/bootstrap-datepicker3.css
    bootstrap_datepicker3_min_css: //cdn.bootcss.com/bootstrap-datepicker/1.6.1/css/bootstrap-datepicker3.min.css
    bootstrap_datepicker_js: //cdn.bootcss.com/bootstrap-datepicker/1.6.1/js/bootstrap-datepicker.js
    bootstrap_datepicker_min_js: //cdn.bootcss.com/bootstrap-datepicker/1.6.1/js/bootstrap-datepicker.min.js
    bootstrap_datepicker_zh_CN_min_js: //cdn.bootcss.com/bootstrap-datepicker/1.6.1/locales/bootstrap-datepicker.zh-CN.min.js

    font_awesome_css: //cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.css
    font_awesome_min_css: //cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css

    holder_js: //cdn.bootcss.com/holder/2.9.3/holder.js
    holder_min_js: //cdn.bootcss.com/holder/2.9.3/holder.min.js

    ionicons_css: //cdn.bootcss.com/ionicons/2.0.1/css/ionicons.css
    ionicons_min_css: //cdn.bootcss.com/ionicons/2.0.1/css/ionicons.min.css

    jquery_js: //cdn.bootcss.com/jquery/2.2.0/jquery.js
    jquery_min_js: //cdn.bootcss.com/jquery/2.2.0/jquery.min.js

    jquery_fancyBox_css: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.css
    jquery_fancyBox_min_css: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
    jquery_fancyBox_js: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.js
    jquery_fancyBox_min_js: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.js
    jquery_fancyBox_pack_js: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.pack.js
    jquery_fancyBox_buttons_css: //cdn.bootcss.com/fancybox/2.1.5/helpers/jquery.fancybox-buttons.css
    jquery_fancyBox_buttons_js: //cdn.bootcss.com/fancybox/2.1.5/helpers/jquery.fancybox-buttons.js
    jquery_fancyBox_media_js: //cdn.bootcss.com/fancybox/2.1.5/helpers/jquery.fancybox-media.js
    jquery_fancyBox_thumbs_css: //cdn.bootcss.com/fancybox/2.1.5/helpers/jquery.fancybox-thumbs.css
    jquery_fancyBox_thumbs_js: //cdn.bootcss.com/fancybox/2.1.5/helpers/jquery.fancybox-thumbs.js

    jquery_nicescroll_min_js: //cdn.bootcss.com/jquery.nicescroll/3.6.7/jquery.nicescroll.min.js

    jquery_ui_css: //cdn.bootcss.com/jqueryui/1.11.4/jquery-ui.css
    jquery_ui_min_css: //cdn.bootcss.com/jqueryui/1.11.4/jquery-ui.min.css
    jquery_ui_js: //cdn.bootcss.com/jqueryui/1.11.4/jquery-ui.js
    jquery_ui_min_js: //cdn.bootcss.com/jqueryui/1.11.4/jquery-ui.min.js

    pace_css: //cdn.bootcss.com/pace/1.0.2/themes/red/pace-theme-flash.css
    pace_js: //cdn.bootcss.com/pace/1.0.2/pace.js
    pace_min_js: //cdn.bootcss.com/pace/1.0.2/pace.min.js
